In [1]:
import numpy as np 

In [2]:
#cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
#criar o array com um tipo esfpecífico
#cria o array como um float de 64bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#mudar o tipo do array
# podemos transformar tipos de dados de arrays

mtnew  = np.array([1.4,3.6,-5.1,9.42,4.9999999])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4        3.6       -5.1        9.42       4.9999999]
[ 1  3 -5  9  4]


In [7]:
#podemos fazer o contrario também 
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [29]:
#Matriz com mais de uma dimenção
#Cria uma matriz bidimencional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)
print("==================")
#mostrar um elemento específico da matriz
print(mt7[0][2])
print("==================")

#mostrar as dimenções da matriz
print(mt7.shape)
print("==================")


[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]
23
(3, 3)


In [14]:
#Criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios

vasio = np.empty([3,2], dtype = int)
print(vasio)
print("---------------")
#cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("---------------")
#como valores igual a um 
um = np.ones([5,7])
print(um)
print("---------------")

#cria matriz quadrada com diagonal prinipal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)


[[28429264711581742 28429397856419958]
 [32088563961561180 32370073299845220]
 [30399774231756907 14355657611083893]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
---------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("=================")
#valores aleatorios distr. normal contendo negativos 
ale2 = np.random.randn((5))
print(ale2)
print("------------")
#valores aleatórios 3x3
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.50571357 0.63431463 0.80166129 0.2488638  0.25936353]
[ 0.95572376  1.56237828 -1.68968433 -0.45711379  1.15871714]
------------
[[6.4960426  9.23644401 0.88457526 3.26375724]
 [3.86146714 8.85514015 9.53675542 2.02480017]
 [9.5516717  2.52425882 8.3465516  3.06749298]]


In [25]:
#outra forma de gerar aleatórios 
#uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [27]:
#unique remover repetições

j = np.array([11,12,13,14,15,16,11,12,13,14,15,16,11,12,13,14,15,16])
j = np.unique(j)
print(j)

[11 12 13 14 15 16]


In [31]:
#funções matemáticas
#Mostrar o maior valor da matriz
print(mt7.max())
#Mostar menor valor
print(mt7.min())
#mostrar soma dos valores da matriz
print(mt7.sum())
#mostrar o valor da média dos valores da matriz
print(mt7.mean())
# mostrar o valor do desvio padrao (standard deviation) dos valores da matriz
print(mt7.std())



34
2
137
15.222222222222221
11.033059188716807


In [32]:
#Funções universais, aplicados a todos os elementos 
#Mostra o valor da raiz quadrada de cada elemento
k1 = np.array([1,4,8,13,32,25])
print(np.sqrt(k1))

#mostra o valor do expoente de todos elementos:
print(np.exp(k1))

[1.         2.         2.82842712 3.60555128 5.65685425 5.        ]
[2.71828183e+00 5.45981500e+01 2.98095799e+03 4.42413392e+05
 7.89629602e+13 7.20048993e+10]


In [ ]:
#extração de elementos
m = np.array([1,2,3,4,5,6])
#Mostra o elemento da posição 2
print(m[1])
