In [6]:
import numpy as np 

In [7]:
#cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [8]:
#criar o array com um tipo esfpecífico
#cria o array como um float de 64bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#mudar o tipo do array
# podemos transformar tipos de dados de arrays

mtnew  = np.array([1.4,3.6,-5.1,9.42,4.9999999])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4        3.6       -5.1        9.42       4.9999999]
[ 1  3 -5  9  4]


In [10]:
#podemos fazer o contrario também 
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [11]:
#Matriz com mais de uma dimenção
#Cria uma matriz bidimencional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)
print("==================")
#mostrar um elemento específico da matriz
print(mt7[0][2])
print("==================")

#mostrar as dimenções da matriz
print(mt7.shape)
print("==================")


[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]
23
(3, 3)


In [12]:
#Criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios

vasio = np.empty([3,2], dtype = int)
print(vasio)
print("---------------")
#cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("---------------")
#como valores igual a um 
um = np.ones([5,7])
print(um)
print("---------------")

#cria matriz quadrada com diagonal prinipal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)


[[2337214414352378226 2334400029607685987]
 [7953758767938674785 7810489035607139885]
 [2315525748462723193 2336916743122085218]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
---------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("=================")
#valores aleatorios distr. normal contendo negativos 
ale2 = np.random.randn((5))
print(ale2)
print("------------")
#valores aleatórios 3x3
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.74733612 0.66808233 0.56551189 0.85953423 0.32088777]
[-1.80255968  0.8830041   1.45685272  0.32200487  1.3056828 ]
------------
[[2.44899426 2.3484643  6.58036022 2.0843006 ]
 [0.90989129 8.45545324 4.89992131 3.62556154]
 [1.94342597 3.07491877 2.30589725 3.65743845]]


In [14]:
#outra forma de gerar aleatórios 
#uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [15]:
#unique remover repetições

j = np.array([11,12,13,14,15,16,11,12,13,14,15,16,11,12,13,14,15,16])
j = np.unique(j)
print(j)

[11 12 13 14 15 16]


In [16]:
#funções matemáticas
#Mostrar o maior valor da matriz
print(mt7.max())
#Mostar menor valor
print(mt7.min())
#mostrar soma dos valores da matriz
print(mt7.sum())
#mostrar o valor da média dos valores da matriz
print(mt7.mean())
# mostrar o valor do desvio padrao (standard deviation) dos valores da matriz
print(mt7.std())



34
2
137
15.222222222222221
11.033059188716807


In [17]:
#Funções universais, aplicados a todos os elementos 
#Mostra o valor da raiz quadrada de cada elemento
k1 = np.array([1,4,8,13,32,25])
print(np.sqrt(k1))

#mostra o valor do expoente de todos elementos:
print(np.exp(k1))

[1.         2.         2.82842712 3.60555128 5.65685425 5.        ]
[2.71828183e+00 5.45981500e+01 2.98095799e+03 4.42413392e+05
 7.89629602e+13 7.20048993e+10]


In [18]:
#extração de elementos
m = np.array([1,2,3,4,5,6])
#Mostra o elemento da posição 2
print(m[1])
print("-----------------")
#mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-----------------")
# Mostra o array criado a partir da 2a posição, até o final
print(m[2:])
print("-----------------")
#mostra o array criado a partir da antepenultima posição
print(m[-3:])



2
-----------------
[1 2]
-----------------
[3 4 5 6]
-----------------
[4 5 6]


In [ ]:
#extração de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("===========")
#Imprimindo linhas de 1 a 3
l_linha_1 = l[0,:]
print(l_linha_1)
print("===========")

l_linha_2 = l[1,:]
print(l_linha_2)
print("===========")

l_linha_3 = l[1,:]
print(l_linha_3)
print("===========")

#imprindo coluna 1 e 2
l_coluna_1 = l[:,0]
print(l_coluna_1)
print("===========")
l_coluna_2 = l[:,1]
print(l_coluna_2)
print("===========")



[[4 5]
 [6 1]
 [7 4]]
[4 5]
[6 1]
[6 1]
[4 6 7]
[5 1 4]


In [20]:
#adição e multiplicação de matrizer

n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])

res1 =  n+o
print(res1)
print("-----------")
res2 = n*o
print(res2)
print("-----------")
p = np.array([[1,2],[3,4],[5,4]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
-----------
[[1 2]
 [3 4]]
-----------
[[3 3]
 [5 5]
 [7 5]]


In [ ]:
#Transpoisição de matriz

f = np.arange(15).reshape((3,5))
print(f)
print("=====================")
print(f.T)
print("=====================")
print(f.transpose((1,0)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
